<?php

########################################################################
# Extension Manager/Repository config file for ext: "library"
#
# Auto generated by Extbase Kickstarter 2010-05-27
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'library',
	'description' => 'Library based on tt_news.',
	'category' => 'plugin',
	'author' => 'Dmitri Pisarev',
	'author_email' => 'dimaip@gmail.com',
	'author_company' => 'SFI',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,mvc_extjs',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'mvc_extjs' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>